-- Enable UUID extension (Good practice for Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. News Table
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    category TEXT,
    date TEXT,
    imageUrl TEXT,
    excerpt TEXT,
    content TEXT,
    author TEXT,
    videoUrl TEXT,
    audioUrl TEXT,
    attachments TEXT, -- Stored as JSON string, consider using JSONB in Postgres later
    metaTitle TEXT,
    metaDescription TEXT,
    keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Library Table
CREATE TABLE IF NOT EXISTS library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    type TEXT,
    description TEXT,
    tag TEXT,
    image_url TEXT,
    link TEXT,
    author TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tools Table
CREATE TABLE IF NOT EXISTS tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    description TEXT,
    icon TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Pricing Table
CREATE TABLE IF NOT EXISTS pricing (
    id TEXT PRIMARY KEY,
    name TEXT,
    price TEXT,
    period TEXT,
    description TEXT,
    features TEXT, -- Stored as JSON string
    ctaText TEXT,
    type TEXT,
    isPopular INTEGER DEFAULT 0
);

-- 6. Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    email TEXT,
    phone TEXT,
    service TEXT,
    note TEXT,
    company TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    client TEXT,
    location TEXT,
    service_type TEXT,
    description TEXT,
    challenge TEXT,
    solution TEXT,
    result TEXT,
    images TEXT, -- Stored as JSON string
    completion_date TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT -- Stored as JSON string
);

-- RLS Policies (Optional: Enable Row Level Security)
-- ALTER TABLE news ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Public can read news" ON news FOR SELECT USING (true);
