-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table
create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique,
  password_hash text,
  role text default 'user',
  created_at timestamptz default now()
);

-- News Table
create table if not exists news (
  id bigint generated by default as identity primary key,
  title text,
  category text,
  date text, -- Keeping as text to match existing format, consider converting to date
  image_url text, -- Standardizing snake_case
  excerpt text,
  content text,
  author text,
  video_url text,
  audio_url text,
  attachments text, -- JSON string
  meta_title text,
  meta_description text,
  keywords text,
  created_at timestamptz default now()
);

-- Library Table
create table if not exists library (
  id bigint generated by default as identity primary key,
  title text,
  type text,
  description text,
  tag text,
  image_url text,
  link text,
  author text,
  content text,
  created_at timestamptz default now()
);

-- Tools Table
create table if not exists tools (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  icon text,
  link text,
  created_at timestamptz default now()
);

-- Pricing Table
create table if not exists pricing (
  id text primary key,
  name text,
  price text,
  period text,
  description text,
  features text, -- JSON string
  cta_text text, -- Standardizing snake_case
  type text,
  is_popular integer
);

-- Contacts Table
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  service text,
  note text,
  company text,
  created_at timestamptz default now()
);

-- Projects Table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  title text,
  client text,
  location text,
  service_type text,
  description text,
  challenge text,
  solution text,
  result text,
  images text, -- JSON string
  completion_date text,
  content text,
  scope_of_work text,
  status text default 'published',
  source_id text unique, -- For sync webhook
  created_at timestamptz default now()
);

-- Settings Table
create table if not exists settings (
  key text primary key,
  value text -- JSON string
);

-- Row Level Security (RLS) Policies
-- Enable RLS on all tables
alter table users enable row level security;
alter table news enable row level security;
alter table library enable row level security;
alter table tools enable row level security;
alter table pricing enable row level security;
alter table contacts enable row level security;
alter table projects enable row level security;
alter table settings enable row level security;

-- Public Read Access Policies (Adjust as needed)
create policy "Public Read News" on news for select using (true);
create policy "Public Read Library" on library for select using (true);
create policy "Public Read Tools" on tools for select using (true);
create policy "Public Read Pricing" on pricing for select using (true);
create policy "Public Read Projects" on projects for select using (true);
create policy "Public Read Settings" on settings for select using (true);

-- Admin Write Access (Assuming Service Role or specific logic, here defaulting to false for public anon)
-- For backend (Service Role) access, it bypasses RLS automatically.
-- If integrating Frontend Auth, add policies based on auth.uid()
